config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { registrations: 'registrations' }
   resources :articles do
     resources :comments
   end
   resources :contacts
  root to: 'articles#index'
  get 'pages/about'
  get 'pages/contact'


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :update , Article do |article|
          article.user == user
        end
        can :destroy, Article do |article|
          article.user == user
        end
        can :update , Comment do |comment|
          comment.user == user
        end
        can :destroy, Comment do |comment|
          comment.user == user
        end
        can :create, Article
        can :create, Comment
        can :read, :all
      end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :user, presence: true
  validates_presence_of :title, uniqueness: true
  validates_presence_of :title, length: {minimum:5, maximum: 70}
  validates_presence_of :body, length: {minimum: 10}

  has_attached_file :image, styles: { medium: "600x600>", thumb: "300x350>" } , default_url: "http://i.imgur.com/qIMxAcFs.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :body, length: {minimum: 5, maximum: 500}
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates_presence_of :name, :email, :message
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         validates :username, presence: true
         validates :email, presence: true
         validates_uniqueness_of :username, :email

         has_many :articles
         has_many :comments
         
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" } , default_url: "http://i.imgur.com/qIMxAcFs.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path
    flash[:danger]= "Sorry, your not authorized to acess this page"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.paginate(:page => params[:page], :per_page => 5).order('updated_at DESC')
    @recent = Article.order('updated_at DESC').last(5)

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @recent = Article.order('updated_at DESC').last(4)
  end

  # GET /articles/new
  def new
    @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
    authorize! :edit, @article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    authorize! :update, @article
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    authorize! :destroy, @article
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :image)

    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource param_method: :my_sanitizer
  load_and_authorize_resource :through => :current_user

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:body))
    @comment.user_id = current_user.id if current_user
    if @comment.save
      redirect_to article_path(@article), notice: "Your comment has been saved"
    else
      redirect_to @article
      flash[:warning]= "There was a problem saving your comment, minimum characters is 5 and the maximum is 500"
    end
  end

  def update
 @article = Article.find(params[:article_id])
 @comment = @article.comments.find(params[:id])

 if @comment.update(params[:comment].permit(:body))
 redirect_to article_path(@article), notice: "Your comment has been updated."
 else
 render 'edit'
  end

end

  def edit
   @article = Article.find(params[:article_id])
   @comment = @article.comments.find(params[:id])
end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), notice: "Your comment has been deleted"
  end
  private

    def my_sanitizer
      params.require(:comment).permit(:body)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

      if @contact.save
        redirect_to root_path
        name = params[:contact][:name]
        email = params[:contact][:email]
        message = params[:contact][:message]
        ContactMailer.contact_email(name, email, message).deliver
        flash[:success] = "Thanks for the message, we will be in touch soon."
      else
        redirect_to pages_contact_path
        flash[:danger] = "Opps, there was a problem! Please fill out all the fields."

      end
  end



    private

    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Article.all.paginate(:page => params[:page], :per_page => 5).order('updated_at DESC')
  end

  def about
  end

  def contact
    @contact = Contact.new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
    def sign_up_params
      params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :username,
      :firstname,
      :lastname,
      :avatar,
      :url

 )

end

 def account_update_params
   params.require(:user).permit(
   :email,
   :password,
   :password_confirmation,
   :current_password,
   :username,
   :firstname,
   :lastname,
   :avatar,
   :url

 )
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, label: false, placeholder:"Article Title" %>
    <%= f.input :body, label: false, placeholder:"Content goes here" %>
    <%= f.input :image, as: :image_preview %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary rubberBand" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row">
 <!-- Blog article Content Column -->
 <div class="col-lg-8">
<% @articles.each do |article| %>
 <!-- Blog article -->
<%= image_tag article.image.url, class: "img-responsive" %>
 <center><h4 style="font-size: 25.5px;"><%= link_to truncate(article.title, length: 50), article %></h4></center>
 <span class="glyphicon glyphicon-time media-heading pull-right"><%= time_ago_in_words(article.created_at)%> ago</span>
 <!-- Date/Time -->
 </p>
 <p>
   <%= image_tag article.user.avatar.url(:thumb), class:"img-responsive" %>By:<strong> <%= article.user.username %></strong>

 <hr>
<%=truncate(article.body, length: 200)%>
<hr>
<% end %>
<%= link_to "New article", new_article_path, class: "btn btn-primary btn-xs" %>
 </div>

<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
 <div class="well commentcolor">
 <h4>Recent articles</h4>
 <% @recent.each do |a| %>
 <strong><%= link_to truncate(a.title, length: 30), a %></strong><br />
 Created by: <%= a.user.username %>
 <p><%= truncate(a.body, length:100) %></p>
 <% end %>
 </div>
</div>
</div>
<br>
<%= will_paginate @article %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="row">
 <!-- Blog Post Content Column -->
 <div class="col-lg-8">
<%= image_tag @article.image.url, class: "img-responsive" %>
 <!-- Blog Post -->
 <!-- Title -->
 <h1 style="font-size: 25.5px;">
 <%= truncate(@article.title, length: 120) %>
 </h1>
 <!-- Author -->
 <p class="lead">
   <%= image_tag @article.user.avatar.url(:thumb), class:"img-responsive" %>
   </p>
by: <%= @article.user.username %>
 <hr>
 <!-- Date/Time -->
 <p><span class="glyphicon glyphicon-time"></span> Was Posted: <%=time_ago_in_words(@article.created_at)%> ago</P>

 <hr>


<%= @article.body %>
<hr>

<% if can? :update, @article %>
<%= link_to 'Edit', edit_article_path(@article), class:"btn btn-primary btn-xs rubberBand" %>
<% end %>

<% if can? :destroy, @article %>
<%= link_to 'Delete', @article, method: :delete, data:{confirm: "Are you sure ?"}, class:"btn btn-danger btn-xs rubberBand" %>
<% end %>

<%= link_to 'Back', articles_path, class:"btn btn-primary btn-xs rubberBand" %>

 <hr>
<br />
 <div class="well commentcolor">
 <!-- Blog Comments -->
 <%= render @article.comments%>
 <!-- Comments Form -->
 <p><p/>
 <%= render 'comments/form' %>
<h4></h4>
 </div>
 <hr>
 <!-- Posted Comments -->
 <!-- Comment -->
 </div>
 <!-- Blog Sidebar Widgets Column -->
 <div class="col-md-4">
 <!-- Blog Search Well -->

 <!-- Blog Categories Well -->

 <!-- Side Widget Well -->
 <div class="well commentcolor">
   <h4>Recent articles</h4>
    <% @recent.each do |a| %>
   Created by: <%= a.user.username %><br />
   <strong><%= link_to truncate(a.title, length: 30), a %></strong>
   <p><%= truncate(a.body, length:100) %></p>
   <% end %>
 </div>
 </div>
</div>

app/views/comments/_comment.html.erb
<div class="media round">
<div class="pull-left">
  <%= comment.user.username %>
  <%= image_tag comment.user.avatar.url(:thumb), class:"img-responsive" %>
</div>
<div class="media-body">
  <p class="media-heading pull-right">
<%= time_ago_in_words(comment.created_at)%>
</p><br />

<%= comment.body%>
</div>
</div>
<br />
<% if can? :update, comment%>
<%= link_to ' Edit', edit_article_comment_path(comment.article, comment), class: "btn btn-primary btn-xs round" %>
<% end %>
<% if can? :destroy, comment%>
<%= link_to 'Delete', [comment.article, comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs round" %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.new]) do |f| %>
<%= f.input :body, label: false, placeholder:"write your comment here" %>
<%= f.submit "Post your comment",class: "btn btn-primary rubberBand"%>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for ([@article, @comment]) do |f|%>
<%= f.input :body %>
<%= f.submit "Submit", class:"btn btn-primary"%>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer-distributed navbar-fixed-bottom">

	<div class="footer-right">

		<a href="#"><i class="fa fa-facebook"></i></a>
		<a href="#"><i class="fa fa-twitter"></i></a>
		<a href="#"><i class="fa fa-linkedin"></i></a>
		<a href="#"><i class="fa fa-github"></i></a>

	</div>

	<div class="footer-left">

		<p class="footer-links">


			<%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
			·
			<%= link_to "About Us", pages_about_path, class: "page-scroll" %>


		</p>

    <p>   </p>
    </div>

</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RoR Blog",root_path, class:"navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#"> link<span class="sr-only">(current)</span></a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign In", new_user_session_path if !current_user %></li>
        <li><%= link_to "Sign Up", new_user_registration_path if !current_user %></li>
        <li><%= link_to "View Article", articles_path%></li>
        <li><%= link_to "About Us", pages_about_path%></li>
        <li><%= link_to "Contact Us", pages_contact_path%></li>
<% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
          role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><%= link_to "Edit my profile", edit_user_registration_path%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
          </ul>
        </li>
      </ul>
      <%end%>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR Blog</title>
    <%= csrf_meta_tags %>
    <head>
  <link rel="stylesheet"
  
</head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav'%>
  <%= bootstrap_flash %>
<div class='container'>
    <%= yield %>

</div>
<%= render'layouts/footer'%>
  </body>
</html>

app/views/pages/_mailer.html.erb
<div class="row">
 <div class="col-md-4 col-md-offset-4">
   <div class="well">
     <%= simple_form_for @contact do |f| %>
     <%= f.input :name %>
     <%= f.input :email %>
     <%= f.input :message %>
     <%= f.submit "Get in touch!", class: " rubberBand btn btn-primary" %>
     <% end %>
   </div>
 </div>
</div>

app/views/pages/about.html.erb
<!--About Page-->
<div class="row">
 <div class="col-lg-12 text-center">
 <h1>About Us</h1>
 <p class="lead">Test Text</p>
 <ul class="list-unstyled">
 <li></li>
 <li></li>
 </ul>
 </div>
</div>

app/views/pages/contact.html.erb
<!--Contact Page-->
<div class="row">
 <div class="col-lg-12 text-center">
 <h1>Contact Us</h1>
 <p class="lead"></p>
 <ul class="list-unstyled">
 <!-- <li>List Item</li>
 <li>List Item 2</li> -->
 </ul>
 </div>
 <%= render'pages/mailer'%>
</div>

app/views/pages/index.html.erb
<div class="row">
 <div class="col-lg-8">
 <!-- Blog Post -->
 <!-- Title -->
<div class="jumbotron commentcolor">
 <h1>Welcome to My . </h1>
 <p>Awesome applications built with Rails!</p>
 <p></p>
</div>

 </div>
 <!-- Blog Sidebar Widgets Column -->
 <div class="col-md-4">
 <!-- Blog Categories Well -->
 <!-- Side Widget Well -->
 <div class="well commentcolor">
 <h4>Recent Posts</h4>
 <% @articles.each do |a| %>
  by: <%= a.user.username %><br />
 <strong><%= link_to truncate(a.title, length: 25), a %></strong>
 <p><%= truncate(a.body) %></p>
 <% end %>
 </div>
 </div>
</div>
<!-- /.row -->
<hr>